#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=dwl
export XDG_CURRENT_DESKTOP=dwl

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

tags="${HOME}/.cache/dwltags"
startup () {
	tempdir="/tmp/${USER}/service"
	s6-svscan ${tempdir} <&- \
		& disown
	s6-rc-init \
		-c /home/${USER}/.local/share/s6/rc/compiled \
		-l /tmp/${USER}/s6-rc /tmp/${USER}/service <&- \
		& disown
	s6-rc \
		-l /tmp/${USER}/s6-rc \
		-up change default <&- \
		& disown
}
mkdir -p ${tempdir} && : || :
exec dbus-launch --exit-with-session dwl -s "startup <&-" > ${tags}
